//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpAssignment2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tbl_Product
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }

        [Display(Name = "Product Name")]
        public string ProductName { get; set; }

        public string Category { get; set; }

        [Display(Name = "Product Code")]
        public string ProductCode { get; set; }

        public int Price { get; set; }

        public string Description { get; set; }

        public string Status { get; set; }

        public int Discount { get; set; }

        public string Image { get; set; }

        public HttpPostedFileBase UploadImage { get; set; }

    }
}
